import { command, footprintDef, lib, partTrustReport, type BoardFootprint, type FootprintDef } from '@tracelet/kernel';
import { useEditor, useProject } from '../store/app.js';
import { usePrefs } from '../i18n/index.js';
export function PartTrust({fp}:{fp:BoardFootprint}) {
  const p=useProject(), editor=useEditor(), zh=usePrefs(s=>s.locale).startsWith('zh');
  const def=footprintDef(fp), report=partTrustReport(p).find(r=>r.ref===fp.ref)!;
  const change=(patch:Partial<FootprintDef>)=>editor.dispatch(lib.addLibraryItems({footprints:[{...def,...patch}]}));
  const c=p.schematic.sheets.flatMap(s=>s.components).find(c=>c.id===fp.componentId);
  return <details><summary>{zh?'器件与封装可信度':'Part and footprint trust'}</summary><div className="col" style={{gap:8}}>
    <label>{zh?'数据来源':'Source'}<input className="input" key={def.id} defaultValue={def.provenance?.source ?? ''} onBlur={e=>change({provenance:{...def.provenance,source:e.target.value,verified:false}})}/></label>
    <label>{zh?'数据手册':'Datasheet'}<input className="input" defaultValue={def.provenance?.datasheet ?? ''} onBlur={e=>change({provenance:{...def.provenance,source:def.provenance?.source ?? '',datasheet:e.target.value,verified:false}})}/></label>
    <label><input type="checkbox" checked={def.provenance?.verified ?? false} disabled={!def.provenance?.source} onChange={e=>change({provenance:{...def.provenance,source:def.provenance?.source ?? '',verified:e.target.checked}})}/>{zh?'已人工核对数据手册':'Manually checked against datasheet'}</label>
    <label>{zh?'连接器安装方向':'Connector mounting'}<select className="input" value={def.connector?.mounting ?? ''} onChange={e=>change({connector:e.target.value ? {mounting:e.target.value as 'horizontal'|'vertical',direction:0,clearance:3}:undefined})}><option value="">{zh?'未指定':'Unspecified'}</option><option value="horizontal">{zh?'卧式，朝板边':'Horizontal, board edge'}</option><option value="vertical">{zh?'立式':'Vertical'}</option></select></label>
    {def.connector && <label>{zh?'局部插拔方向 °':'Local mating direction °'}<input type="number" className="input" value={def.connector.direction} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))change({connector:{...def.connector!,direction:e.target.valueAsNumber}});}}/></label>}
    <span className="small muted">{zh?'实体轮廓':'Physical body'}: {def.physicalBody ? `${def.physicalBody.w} × ${def.physicalBody.h} mm` : (zh?'未提供':'Not provided')} · {zh?'缺失映射':'Missing mappings'}: {report.missingPins.join(', ')||'—'}</span>
    {c && <label>{zh?'原理图功能分组':'Schematic functional group'}<input className="input" defaultValue={c.props.group??''} onBlur={e=>{const group=e.target.value;if(group===(c.props.group??''))return;editor.dispatch(command('Functional group',p=>({...p,schematic:{...p.schematic,sheets:p.schematic.sheets.map(s=>({...s,components:s.components.map(x=>x.id===c.id?{...x,props:{...x.props,group}}:x)}))}})));}}/></label>}
    {c && <label><input type="checkbox" checked={['true','yes','1'].includes((c.props.dnp??c.props.DNP??'').toLowerCase())} onChange={e=>{const dnp=e.target.checked?'true':'false';editor.dispatch(command('DNP',p=>({...p,schematic:{...p.schematic,sheets:p.schematic.sheets.map(s=>({...s,components:s.components.map(x=>x.id===c.id?{...x,props:{...x.props,DNP:dnp,dnp}}:x)}))}})));}}/>{zh?'不装配（DNP）':'Do not populate (DNP)'}</label>}
    <div className="small muted">{zh?'实体轮廓（只改外形，不移动焊盘）':'Physical body (does not move pads)'}</div>
    {(['w','h','x','y'] as const).map(axis=><label key={axis}>{axis} / mm <input type="number" className="input" value={(def.physicalBody??def.body)[axis]??0} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&(!['w','h'].includes(axis)||n>0))change({physicalBody:{...(def.physicalBody??def.body),[axis]:n},provenance:{...def.provenance,source:def.provenance?.source??'',verified:false}});}}/></label>)}
    {c && <label>{zh?'引脚→焊盘映射 JSON（空白恢复同号映射）':'Pin → pad mapping JSON (blank for same numbers)'}<textarea className="input" key={c.id+JSON.stringify(c.pinMap)} defaultValue={c.pinMap ? JSON.stringify(c.pinMap):''} onBlur={e=>{try { const pinMap=e.target.value.trim() ? JSON.parse(e.target.value) : undefined; if(pinMap && (typeof pinMap!=='object'||Array.isArray(pinMap)||Object.values(pinMap).some(v=>typeof v!=='string')))throw Error('Expected string mapping'); editor.dispatch(command('Pin mapping',p=>({...p,schematic:{...p.schematic,sheets:p.schematic.sheets.map(s=>({...s,components:s.components.map(x=>x.id===c.id?{...x,pinMap}:x)}))}}))); e.target.setCustomValidity(''); } catch {e.target.setCustomValidity('Invalid JSON mapping');e.target.reportValidity();}}}/></label>}
    {def.modelPlacement && <span className="xs muted">{zh?'导入模型偏移（mm）':'Imported model offset (mm)'}: {def.modelPlacement.offset.join(', ')}<br/>{def.modelPlacement.source}</span>}
  </div></details>;
}
