import { ruleSetOf, type Project } from '../model/project.js';
import { planPanel, type PanelOptions } from '../board/panel.js';
import { exportFabFiles, GerberWriter, type FabFile } from './gerber.js';
import { manufacturingBoard, validateAssembly } from './manufacturing.js';
import { exportBomCsv, exportPickAndPlaceCsv } from './netlist.js';

/** Merge only the explicit absolute-coordinate subset generated by our writer. */
export function mergeGeneratedGerbers(sources:string[]):string {
  let next=10;
  return sources.map((source,index)=>{
    const codes=new Map<string,string>();
    for(const m of source.matchAll(/%ADD(\d+)/g))codes.set(m[1],String(next++));
    return '%LPD*%\n'+source.split('\n').filter(l=>l!=='M02*' && !(index>0 && /^%TF\./.test(l))).map(l=>l.replace(/%ADD(\d+)/g,(_,n)=>`%ADD${codes.get(n)}`).replace(/^D(\d+)\*$/,(_,n)=>`D${codes.get(n)??n}*`)).join('\n');
  }).join('\n')+'\nM02*\n';
}
function mergeDrills(sources:string[]):string {
  const definitions:string[]=[],hits:string[]=[];let next=1;
  for(const s of sources){
    const codes=new Map<string,string>();
    for(const line of s.split('\n')){
      const tool=/^T(\d+)C([\d.]+)$/.exec(line);
      if(tool){const id=String(next++);codes.set(tool[1],id);definitions.push(`T${id}C${tool[2]}`);continue;}
      const select=/^T(\d+)$/.exec(line);if(select && codes.has(select[1]))hits.push(`T${codes.get(select[1])}`);
      if(/^X[-\d.]+Y[-\d.]+$/.test(line))hits.push(line);
    }
  }
  return ['M48','METRIC',...definitions,'M95','G90','G05',...hits,'T0','M30',''].join('\n');
}
export function exportPanelFiles(project:Project,options:PanelOptions):FabFile[] {
  const issues=validateAssembly(project);if(issues.length)throw new Error(issues.map(i=>`${i.code}: ${i.refs.join(', ')}`).join('; '));
  const plan=planPanel(project.board,options,ruleSetOf(project));
  if(plan.errors.length)throw new Error(plan.errors.join('; '));
  // Depth-specific operations cannot safely be collapsed into ordinary drill files.
  if(project.board.vias.some(v=>v.backdrill || v.startLayer || v.endLayer))throw new Error('Panel export currently supports through drills only');
  const grouped=new Map<string,{kind:FabFile['kind'];sources:string[]}>();
  const assembly=structuredClone(project);assembly.board.footprints=[];assembly.schematic.sheets=[];
  assembly.settings.manufacturing={origin:{x:0,y:0},bottomRotation:project.settings.manufacturing?.bottomRotation??'top-view',includeDnp:project.settings.manufacturing?.includeDnp??false};
  for(const instance of plan.instances){
    const copy:Project={...project,settings:{...project.settings,manufacturing:{...assembly.settings.manufacturing!,origin:{x:-instance.x,y:-instance.y}}},board:{...project.board,footprints:project.board.footprints.map(f=>({...f,ref:`${instance.id}_${f.ref}`}))}};
    for(const file of exportFabFiles(copy,{bom:false,pnp:false})){
      if(!['gerber','drill'].includes(file.kind)||file.name.endsWith('.gm1'))continue;
      const item=grouped.get(file.name)??{kind:file.kind,sources:[]};item.sources.push(file.content);grouped.set(file.name,item);
    }
    assembly.board.footprints.push(...manufacturingBoard(copy).footprints.map(f=>({...f,id:`${instance.id}_${f.id}`,componentId:f.componentId?`${instance.id}_${f.componentId}`:undefined})));
    assembly.schematic.sheets.push(...project.schematic.sheets.map(s=>({...s,id:`${instance.id}_${s.id}`,components:s.components.map(c=>({...c,id:`${instance.id}_${c.id}`,ref:`${instance.id}_${c.ref}`}))})));
  }
  const tooling=[{x:options.rail/2,y:options.rail/2},{x:plan.width-options.rail/2,y:options.rail/2},{x:options.rail/2,y:plan.height-options.rail/2}];
  const drill=['M48','METRIC','T1C0.500','T2C1.500','M95','G90','G05','T1',...plan.holes.map(p=>`X${p.x.toFixed(4)}Y${(-p.y).toFixed(4)}`),'T2',...tooling.map(p=>`X${p.x.toFixed(4)}Y${(-p.y).toFixed(4)}`),'M30'].join('\n');
  const npth=[...grouped].find(([name])=>name.endsWith('-NPTH.drl'))!;npth[1].sources.push(drill);
  for(const [suffix,fn,dia] of [['.gtl','Copper,L1,Top',1],['.gts','Soldermask,Top',2]] as const){
    const w=new GerberWriter(fn,suffix==='.gts'?'Negative':'Positive'),ap=w.circle(dia);plan.fiducials.forEach(p=>w.flash(ap,p));
    [...grouped].find(([name])=>name.endsWith(suffix))![1].sources.push(w.toString());
  }
  const profile=new GerberWriter('Profile,NP'),pen=profile.circle(0.1);plan.profile.forEach(r=>profile.polyline(pen,[...r,r[0]]));
  return [...grouped].map(([name,item])=>({name:`panel-${name}`,kind:item.kind,content:item.kind==='drill'?mergeDrills(item.sources):mergeGeneratedGerbers(item.sources)})).concat([
    {name:'panel-Edge_Cuts.gm1',kind:'gerber',content:profile.toString()},
    {name:'panel-BOM.csv',kind:'bom',content:exportBomCsv(assembly)},
    {name:'panel-PickAndPlace.csv',kind:'pnp',content:exportPickAndPlaceCsv(assembly)},
    {name:'panel-manifest.json',kind:'readme',content:JSON.stringify({...plan,tooling,units:'mm',xy:'X right, Y up in Gerber/drill/placement; plan coordinates Y down',rotation:assembly.settings.manufacturing.bottomRotation,sourceProject:project.id,sourceUpdatedAt:project.updatedAt,notes:'0.5 mm mouse bites, 1.5 mm tooling holes, 1 mm top fiducials with 2 mm mask openings and no paste. Straight milling contours; fabricator must confirm router radius, breakaway strength and assembly rotation.'},null,2)}
  ]);
}
