/** Public product documentation. Keep private deployment details out of this module. */
export type DocLanguage = 'zh-CN' | 'en';
type Text = [string, string];
export const docText = (text: Text, language: DocLanguage) => text[language === 'zh-CN' ? 0 : 1];
export interface DocSection { id: string; title: Text; intro: Text; blocks: { title: Text; body: Text; steps?: Text[]; code?: string }[] }
export const sections: DocSection[] = [
  { id: 'overview', title: ['认识 Tracelet', 'Meet Tracelet'], intro: ['从想法到制造文件，一个浏览器工作区。', 'From an idea to fabrication files, in one browser workspace.'], blocks: [
    { title: ['轻量，但流程完整', 'Lightweight, with a complete workflow'], body: ['Tracelet 是面向个人、极客与小团队的开源 EDA。应用和设计内核采用 TypeScript，Web 编辑器使用 React。构建后的静态网页即可运行本地设计，不要求安装桌面 EDA、数据库或下载整套离线器件库。', 'Tracelet is an open-source EDA for individuals, makers and small teams. The application and design kernel use TypeScript; the web editor uses React. A static web build runs local design without a desktop EDA installation, database or full offline component library.'] },
    { title: ['你可以做什么', 'What you can do'], body: ['多页原理图、器件库、2 / 4 / 6 层 PCB、布局与布线辅助、ERC / DRC、3D、BOM、制造、装配与测试。还可用 AI 生成原理图草案，用 CLI 和 MCP 复用设计内核。默认本地保存，远程存储按需启用。', 'Work with multi-sheet schematics, libraries, 2 / 4 / 6-layer PCBs, assisted placement and routing, ERC / DRC, 3D, BOM, fabrication, assembly and test views. AI can draft a schematic; CLI and MCP expose the design kernel. Storage is local by default, with an optional remote service.'] },
    { title: ['使用前了解边界', 'Understand the boundaries'], body: ['自动化结果需要工程复核。自动布线不保证全通或无干扰；阻抗、温升是估算而非场求解或整板热仿真；未匹配的 3D 模型显示为占位。远程存储不等于多人实时协同编辑。', 'Automation requires engineering review. Autorouting does not guarantee completion or interference-free signals. Impedance and temperature tools are estimates, not field solvers or whole-board thermal simulation. Missing 3D assets use placeholders. Remote storage is not simultaneous collaborative editing.'] }
  ] },
  { id: 'quickstart', title: ['快速开始', 'Quick start'], intro: ['先完成一块小板，再探索高级功能。', 'Start with a small board, then explore advanced features.'], blocks: [
    { title: ['第一条完整设计流程', 'Your first complete design'], body: ['直接打开 tracelet.org 或本地运行的网页，按下面的顺序操作。', 'Open tracelet.org or your local web app and follow these steps.'], steps: [
      ['首页选择“创建新项目”，设置名称、层数、单位与板厂规则；也可以使用模板。', 'Choose New project on the home page and set a name, layers, units and fabrication rules, or start from a template.'],
      ['在原理图放置元件、连接引脚并命名网络，查看 ERC，核对电源及封装。', 'Place schematic components, connect pins and name nets. Review ERC, power connections and footprints.'],
      ['在右侧属性面板选择“同步到 PCB”，生成或更新板上的元器件。', 'Choose Update PCB in the right properties panel to create or update board components.'],
      ['确定板框和缺口，核对接口与天线方向，预览布局优化建议后再应用。', 'Define the outline and notches, verify connector and antenna orientation, then preview and apply placement suggestions.'],
      ['设置网络类并布线，重新填充铺铜，检查未连通网络和 DRC。', 'Set net classes and route. Refill copper zones and check remaining connections and DRC.'],
      ['检查 3D、BOM 和制造报告，回读 Gerber 后导出制造 ZIP，同时备份项目。', 'Review 3D, BOM and fabrication reports. Inspect the Gerber readback, export the fabrication ZIP and back up your project.'] ] },
    { title: ['四种项目入口', 'Four ways to start'], body: ['空白项目适合自由设计；模板适合学习；导入用于继续已有工程；AI 创建先分析需求和器件组成，确认方案后才生成新原理图，不会直接生成已完成的 PCB。', 'Start blank for full control, use a template to learn, import an existing design, or create with AI. AI first proposes components from your requirements; you review the plan before generating a new schematic. It does not create a finished PCB.'] }
  ] },
  { id: 'interface', title: ['交互界面导览', 'Interactive interface tour'], intro: ['点击下方示意图中的区域，了解它在设计流程中的作用。示意图不修改你的项目。', 'Select a region in the diagram to learn its role. This illustration does not modify your project.'], blocks: [] },
  { id: 'install', title: ['安装与本地运行', 'Install and run locally'], intro: ['只使用在线版本无需安装。开发或自托管时再构建源码。', 'The online app needs no installation. Build the source for development or self-hosting.'], blocks: [
    { title: ['准备环境', 'Prerequisites'], body: ['安装 Git、Node.js 20 或更新版本，以及 pnpm 10.30.1（仓库 packageManager 指定版本）。在终端执行：', 'Install Git, Node.js 20 or newer, and pnpm 10.30.1, the version specified by packageManager. Run in a terminal:'], code: 'git clone https://github.com/gongbin/tracelet.git\ncd tracelet\npnpm install\npnpm dev' },
    { title: ['验证生产构建', 'Check a production build'], body: ['开发服务默认地址为 http://localhost:5173，端口占用时以终端输出为准。生产文件在 apps/web/dist。preview 适合本地检查构建，不是生产服务进程。不要直接双击 index.html。', 'The development URL defaults to http://localhost:5173; check the terminal if the port is busy. Production files are in apps/web/dist. The preview command is for local build checks, not production serving. Do not open index.html as a file.'], code: 'pnpm build\npnpm --filter @tracelet/web preview\n\n# Development checks\npnpm typecheck\npnpm test' }
  ] },
  { id: 'projects', title: ['项目、导入与备份', 'Projects, import and backup'], intro: ['本地模式下，项目属于当前浏览器和当前站点。', 'Local projects belong to the current browser and site origin.'], blocks: [
    { title: ['导入已有工程', 'Import an existing project'], body: ['从首页“导入”选择文件或拖入文件。KiCad 工程建议同时选择所有 .kicad_sch 与 .kicad_pcb，也可导入工程 ZIP；Altium 选择 .SchDoc 与 .PcbDoc；EasyEDA 标准版使用导出的 JSON。Tracelet 的 .eda.json 与备份 ZIP 可用于迁移。', 'Choose Import or drop files onto the home page. For KiCad, select all .kicad_sch files together with the .kicad_pcb, or use a project ZIP. For Altium, select .SchDoc and .PcbDoc. EasyEDA Standard uses exported JSON. Tracelet .eda.json and backup ZIP files support migration.'] },
    { title: ['导入后先核对', 'Review after import'], body: ['检查元件数量、位号、引脚网络、封装、板框和层数。缺失符号或占位封装需要补齐；不能仅凭图形看起来正确就确认连接正确。不同 EDA 的规则、特殊几何和层信息可能存在不支持或近似。', 'Check component counts, references, pin nets, footprints, outline and layer count. Resolve missing symbols and placeholder footprints. A visually correct drawing does not prove electrical correctness. Rules, special geometry and layers from other EDAs may be unsupported or approximated.'] },
    { title: ['备份与跨设备使用', 'Backup and use across devices'], body: ['首页“备份”导出项目备份。清除站点数据、使用隐私窗口或换浏览器可能使本地项目不可见。localhost 与正式域名互不共享本地项目；分享项目 URL 不会把本地文件传给别人，请导出文件或使用同一远程存储。', 'Use Backup on the home page. Clearing site data, using a private window or switching browsers can make local projects unavailable. Localhost and the public domain do not share local data. Sharing a project URL does not transfer its local file; export the project or use the same remote storage.'] }
  ] },
  { id: 'schematic', title: ['原理图编辑', 'Schematic editing'], intro: ['先建立可靠的电气连接，再同步到 PCB。', 'Establish reliable electrical connectivity before updating the PCB.'], blocks: [
    { title: ['放置与连接', 'Place and connect'], body: ['从元件库搜索型号并放置，检查引脚名称、编号、值和封装。使用连线工具点击引脚，沿吸附提示连接到目标引脚；用网络标签和电源符号表达同名网络。单纯线条交叉不一定连通，需检查结点与网表。', 'Search the library and place parts. Check pin names, numbers, values and footprints. With the wire tool, click a pin and follow snapping feedback to the destination. Use net labels and power symbols for named connections. A bare wire crossing is not necessarily connected; check junctions and the netlist.'] },
    { title: ['多页、整理与 ERC', 'Sheets, cleanup and ERC'], body: ['可添加多页图纸、标题栏和注释。整理并校验功能会在应用前核对电气连接身份；整理后仍应审阅文字与分组。ERC 检查引脚类型、未连接等问题；有意悬空的引脚应标注不连接，而非随意接地来消除报警。', 'Add sheets, title blocks and annotations. Cleanup verifies electrical identity before applying changes; review text and grouping afterward. ERC checks issues such as pin types and unconnected pins. Mark deliberately unused pins as no-connect instead of grounding them just to silence warnings.'] },
    { title: ['同步到 PCB', 'Update PCB'], body: ['原理图完成或更改后，在右侧属性面板同步到 PCB。先确认封装和引脚到焊盘的映射，再检查 PCB 的更新结果。移动、旋转、连线及整理等编辑可通过撤销回退。手机上属性面板默认收起，需要手动展开。', 'After schematic changes, update the PCB from the right properties panel. Verify footprints and pin-to-pad mappings, then inspect the result. Edits such as moving, rotating, wiring and cleanup can be undone. On phones, expand the initially collapsed properties panel.'] }
  ] },
  { id: 'pcb', title: ['PCB 布局与布线', 'PCB placement and routing'], intro: ['约束、布局和布线相互影响。先解决布局问题，再追求布通率。', 'Constraints, placement and routing interact. Fix placement before chasing completion.'], blocks: [
    { title: ['板框、层叠和器件方向', 'Outline, stackup and orientation'], body: ['设置板框大小、缺口、层数和工艺参数。使用标尺与对齐吸附整理器件。USB、SD 卡等接口需结合插拔方向贴合合适板边，射频模块应保留数据手册要求的天线净空。先核对器件方向元数据，再应用自动布局。', 'Set board size, notches, layers and process parameters. Use rulers and alignment snapping. Position connectors such as USB and SD slots at suitable edges with the correct insertion direction; preserve the antenna clearance specified by the RF module datasheet. Check orientation metadata before automatic placement.'] },
    { title: ['布局优化', 'Placement optimization'], body: ['预览建议后检查：器件是否重叠或越界，去耦是否靠近供电脚，晶振与相关 IC 是否靠近，开关电源与敏感模拟区域是否分开。器件实体轮廓、插拔方向和天线信息不准确时，应先修正这些信息，不能只反复运行优化。', 'Preview suggestions and check overlaps, board boundaries, decoupling near supply pins, crystals near their ICs, and separation between switching power and sensitive analog regions. Correct body outlines, insertion directions and antenna metadata before rerunning optimization.'] },
    { title: ['手动及自动布线', 'Manual and automatic routing'], body: ['按网络类设定线宽与间距，再运行自动布线；过程支持进度和取消。检查剩余飞线及 DRC，必要时调整器件位置、通道或层数。当前差分成对搜索与长度补偿适用于受支持的双端、等线宽、单层路径，不支持成对过孔换层或分支差分网络。', 'Set net-class width and clearance before autorouting. Progress and cancellation are available. Inspect remaining airwires and DRC; adjust placement, channels or layer count where needed. Differential pair search and length tuning currently apply to supported two-terminal, equal-width, single-layer paths, not paired layer-change vias or branched differential nets.'] },
    { title: ['铺铜与高级工艺', 'Copper zones and advanced processes'], body: ['设置网络、避让、热焊盘间隙和辐条宽，编辑后重新填充并复查连通性。盲埋孔、背钻和阻抗参数需结合板厂层叠确认。软件报告不能代替参考平面连续性、回流路径、EMI 和可制造性的工程判断。', 'Set the net, clearance, thermal gap and spoke width. Refill after edits and recheck connectivity. Confirm blind/buried via, backdrill and impedance parameters against the fabricator stackup. Reports cannot replace engineering review of reference planes, return paths, EMI and manufacturability.'] }
  ] },
  { id: 'library', title: ['器件库与可信度', 'Libraries and component trust'], intro: ['正确的模型和映射，是正确布局与制造的基础。', 'Correct models and mappings underpin placement and fabrication.'], blocks: [
    { title: ['内置、社区与我的零件', 'Built-in, community and personal parts'], body: ['在库页搜索、分类筛选和查看元件详情，可导入 CSV / JSON 零件清单或 KiCad 符号与封装库。检查来源、数据手册、实际封装尺寸及引脚到焊盘映射。不要把同名封装或相似外形当作电气兼容的保证。', 'Search, filter and inspect parts in the library. Import CSV / JSON part lists or KiCad symbol and footprint libraries. Check sources, datasheets, dimensions and pin-to-pad mappings. Similar names or shapes do not guarantee electrical compatibility.'] },
    { title: ['实体与 3D 偏移', 'Body outlines and 3D offsets'], body: ['器件属性可保存实体轮廓、连接器方向和模型偏移。调整实体轮廓不应连带移动焊盘；模型偏移用于校正显示，不能修复错误的 PCB 焊盘位置。缺少信息的器件需要人工核对，不会因为成功渲染就自动可信。', 'Component properties retain body outlines, connector directions and model offsets. Adjusting a body outline should not move pads. A model offset corrects visualization, not incorrect PCB pad locations. A successfully rendered part still requires verification if its metadata is incomplete.'] }
  ] },
  { id: 'ai', title: ['AI 创建与助手', 'AI creation and assistant'], intro: ['让 AI 先提出方案，由你确认设计意图。', 'Let AI propose a plan, then confirm the design intent yourself.'], blocks: [
    { title: ['配置与生成', 'Configure and generate'], body: ['首页点击 AI 创建。没有 Key 或模型配置时会提示配置并定位缺失字段。填写 API Key、模型和可选服务地址；当前调用使用 Anthropic Messages 协议，不能直接将 OpenAI 的 /api/v1 地址当成同一协议。空地址使用默认服务。', 'Choose Create with AI on the home page. Missing key or model settings trigger setup guidance and focus the missing field. Enter an API key, model and optional service URL. Calls use the Anthropic Messages protocol; an OpenAI /api/v1 endpoint is not interchangeable. An empty URL uses the default service.'], steps: [
      ['描述功能、电源、电压、接口和尺寸要求；不确定的器件可让 AI 提议。', 'Describe functions, power, voltages, interfaces and size constraints; ask AI to propose unspecified parts.'],
      ['分析后检查元件组成、封装、引脚及设计备注。需要改需求时重新分析。', 'Review proposed components, footprints, pins and notes. Reanalyze if requirements change.'],
      ['确认后生成独立项目的原理图，再核对数据手册、ERC 和封装，最后同步 PCB。', 'Confirm to generate a schematic in a new project. Check datasheets, ERC and footprints before updating the PCB.'] ] },
    { title: ['数据与结果', 'Data and results'], body: ['Key 保存在当前浏览器配置中；请求内容发送给你选定的 AI 服务。助手也可识别附件并调用编辑工具。生成的引脚、选型与网络都是待核对的草案，不是已验证的电路；请勿将 Key 放入公开项目或截图。', 'The key is saved in the current browser configuration; request content is sent to your selected AI service. The assistant can also interpret attachments and use editing tools. Generated pinouts, part choices and nets are drafts requiring review, not validated circuits. Keep keys out of public projects and screenshots.'] }
  ] },
  { id: 'fabrication', title: ['检查与制造输出', 'Checks and fabrication'], intro: ['以实际导出文件为准，闭环核对设计与制造结果。', 'Review the actual exported files to close the loop between design and manufacturing.'], blocks: [
    { title: ['工程报告', 'Engineering reports'], body: ['制造页展示布局、信号约束、布线、阻抗与热估算等指标。先处理 ERC / DRC 错误与未布通网络，再看评分；未评估不等于通过。阻抗需要真实层叠，直流温升估算还需要热阻等输入，不能据此声称完成信号完整性或整板热验证。', 'The fabrication page reports placement, signal constraints, routing, impedance and thermal estimates. Resolve ERC / DRC errors and unrouted nets before considering scores; unassessed is not passed. Impedance needs a real stackup, and DC temperature estimates need inputs such as thermal resistance. These do not establish signal integrity or whole-board thermal validation.'] },
    { title: ['Gerber、钻孔、BOM 与坐标', 'Gerber, drills, BOM and placement'], body: ['统一导出原点，确认底面旋转约定。BOM 与坐标使用一致的 DNP 策略，并核对缺失、重复和不匹配位号。DNP 不会删除板上的焊盘或铜。回读 Gerber 预览，逐层检查板框、铜、阻焊、丝印，并核对钻孔与装配文件后再提交板厂。', 'Use a consistent export origin and confirm the bottom-side rotation convention. Apply the same DNP policy to BOM and placement files; check missing, duplicate and mismatched references. DNP does not remove board pads or copper. Inspect Gerber readback layer by layer, including outline, copper, mask and silk, then check drills and assembly files before fabrication.'] },
    { title: ['拼板', 'Panelization'], body: ['拼板输出独立制造包，不改变单板。当前以同向阵列生成工艺边、连接桥、鼠咬孔、定位孔和基准点，保护天线、接口与缺口。高级钻孔和不安全的桥接可能被拒绝；连接桥强度、铣刀半径与公差需板厂确认。', 'Panelization exports a separate fabrication package without modifying the single board. Same-orientation arrays include rails, tabs, mouse bites, tooling holes and fiducials while protecting antennas, connectors and notches. Advanced drilling or unsafe tabs may be rejected. Confirm tab strength, cutter radius and tolerances with your fabricator.'] }
  ] },
  { id: '3d', title: ['3D、装配与测试', '3D, assembly and testing'], intro: ['展示外观，也辅助检查器件方向与装配过程。', 'Visualize the product and review orientation and assembly.'], blocks: [
    { title: ['模型与产品渲染', 'Models and product rendering'], body: ['3D 页显示板体、铜、焊盘和元件模型。未匹配时显示占位。打开「3D 模型匹配」，可按型号搜索厂商、KiCad、SnapMagic、Component Search Engine，下载后导入 STEP / STP（≤20 MB）或 GLB（≤8 MB）。STEP 在浏览器本地转换，首次使用按需加载转换器，不上传文件。叠加焊盘预览，核对尺寸、1 脚与接口方向，调整缩放、旋转和偏移，再点击应用并保存；关闭或切换封装会丢弃未保存调整。同名模型自动匹配，近似候选需确认。配置应用于同封装器件，可撤销；来源、许可和文件指纹随项目保存。模型更新后重新导入即可。支持 GLB 导出及独立 PNG 产品渲染，包括顶面、底面、等轴与透明背景。', 'The 3D view shows the board, copper, pads and component models. Open 3D model matching to search manufacturer, KiCad, SnapMagic and Component Search Engine resources by part number. Download and import STEP / STP (≤20 MB) or GLB (≤8 MB). STEP is converted locally; the converter loads on first use and files are not uploaded. Preview against pads, check dimensions, pin 1 and mating direction, then adjust scale, rotation and offsets and apply. Closing or switching footprints discards unsaved adjustments. Exact names match automatically; approximate candidates need confirmation. Assignments apply to components sharing the footprint and support undo. Sources, licenses and file fingerprints stay in the project. Reimport a newer model to update it. Export GLB or independent PNG product renders with top, bottom, isometric and transparent-background options.'] },
    { title: ['装配与板上测试', 'Assembly and board testing'], body: ['装配页提供分组物料、元件高亮与完成标记。测试页生成探测位置和检查建议，不连接测试仪器，也不能确认实板功能已通过。制造前检查连接器开口、极性、器件高度和结构干涉。', 'The assembly page offers grouped parts, highlighting and completion markers. The test page suggests probe locations and checks; it does not control instruments or certify a physical board. Review connector openings, polarity, height and mechanical interference before fabrication.'] }
  ] },
  { id: 'deploy', title: ['自托管部署', 'Self-hosting'], intro: ['网页可独立静态托管；数据库和 API 只在需要远程存储时启用。', 'Host the web app statically; add a database and API only for remote storage.'], blocks: [
    { title: ['部署静态网页', 'Host the static web app'], body: ['完成 pnpm build 后，把 apps/web/dist 的全部内容上传到静态主机。为 /docs 和 /p/... 等路径设置 SPA 回退到 index.html，同时正常提供 JS、CSS 和模型资源。配置域名与 HTTPS。更新时整体替换构建产物并避免长期缓存 index.html。', 'After pnpm build, upload all of apps/web/dist to your static host. Configure SPA fallback to index.html for paths such as /docs and /p/..., while serving JS, CSS and model assets normally. Configure your domain and HTTPS. Replace the build as a unit on updates and avoid long-lived caching of index.html.'], code: '# Example nginx static-site location (inside your server block)\nroot /srv/tracelet/dist;\nlocation / {\n    try_files $uri $uri/ /index.html;\n}' },
    { title: ['可选：远程文件存储', 'Optional: remote file storage'], body: ['在可信服务器检出源码并安装依赖后启动 API。下面的环境变量在运行前替换。默认文件存储目录需持久化并备份；生产中由进程管理器保持服务运行，HTTPS 反向代理将 /api/ 转发到 127.0.0.1:8787，并保留 /api/ 路径和 Authorization 请求头。', 'Check out the source and install dependencies on your server, then start the API. Replace the example environment values. Persist and back up the file directory. In production, use a process manager and an HTTPS reverse proxy forwarding /api/ to 127.0.0.1:8787, preserving the /api/ path and Authorization header.'], code: 'HOST=127.0.0.1 PORT=8787 \\\nTRACELET_DATA_DIR=/srv/tracelet-data \\\nTRACELET_TOKEN="<your-long-random-token>" \\\npnpm --filter @tracelet/server start' },
    { title: ['可选：PostgreSQL', 'Optional: PostgreSQL'], body: ['先创建 PostgreSQL 数据库和专用用户，再设置 DATABASE_URL。服务首次启动会创建所需表，用户需具备相应权限。不要公开数据库端口；备份数据库，并妥善保管令牌。未设置 DATABASE_URL 时使用文件存储。', 'Create a PostgreSQL database and dedicated user, then set DATABASE_URL. The service creates required tables on startup, so the user needs the relevant permissions. Keep the database port private, back up the database and protect the token. Without DATABASE_URL, the service uses file storage.'], code: 'HOST=127.0.0.1 PORT=8787 \\\nDATABASE_URL="postgres://user:password@127.0.0.1:5432/tracelet" \\\nTRACELET_TOKEN="<your-long-random-token>" \\\npnpm --filter @tracelet/server start' },
    { title: ['连接网页与 API', 'Connect the web app to the API'], body: ['在头像菜单的存储设置中选择远程，填写服务地址和相同令牌，测试连接。同域优先使用反向代理；跨域部署时用 CORS_ORIGINS 配置允许的网页来源（逗号分隔）。401 通常是令牌缺失或不一致；不要通过关闭鉴权来解决。远程模式不会自动合并不同浏览器的本地项目，请先备份再迁移。', 'Select remote storage in the avatar menu, enter the service URL and matching token, then test the connection. Prefer a same-origin proxy; for cross-origin hosting, configure CORS_ORIGINS with comma-separated allowed web origins. A 401 usually means a missing or mismatched token; do not disable authentication to fix it. Remote mode does not automatically merge local projects from different browsers; back up before migration.'] }
  ] },
  { id: 'automation', title: ['CLI 与 MCP', 'CLI and MCP'], intro: ['在终端或支持 MCP 的助手中使用同一个设计内核。', 'Use the same design kernel from a terminal or MCP-enabled assistant.'], blocks: [
    { title: ['命令行', 'Command line'], body: ['在仓库目录执行。用 --help 查看当前版本的参数。文件模式修改后会写入目标文件，建议先复制工程。', 'Run from the repository directory. Use --help for current options. File-mode changes write to the target file, so work on a copy first.'], code: 'pnpm cli --help\npnpm cli new demo.eda.json --demo\npnpm cli erc demo.eda.json\npnpm cli drc demo.eda.json\npnpm cli export zip demo.eda.json' },
    { title: ['浏览器实时桥', 'Live browser bridge'], body: ['在 MCP 客户端配置下方启动命令，然后在网页头像菜单开启“本地 Agent（MCP 实时桥）”。连接后先列出项目并确认目标，再请求原理图、布局或布线修改。网页中的修改支持撤销。完整客户端配置与工具列表见仓库 MCP.md。', 'Configure the following launch command in your MCP client, then enable Local Agent (MCP live bridge) in the web avatar menu. List projects and confirm the target before requesting schematic, placement or routing changes. Browser edits support undo. See MCP.md in the repository for client configuration and the tool list.'], code: 'pnpm --dir /path/to/tracelet cli serve --mcp --live' }
  ] },
  { id: 'faq', title: ['常见问题 · FAQ', 'Frequently asked questions'], intro: ['从现象出发，找到下一步检查位置。', 'Start with the symptom and find the next check.'], blocks: [
    { title: ['为什么项目不见了？', 'Why are my projects missing?'], body: ['确认当前域名、浏览器和存储模式是否与创建时一致。检查是否清理站点数据或使用隐私窗口。有备份时从首页导入；本地项目不能仅靠项目链接恢复。', 'Check the domain, browser and storage mode against those used at creation. Check for cleared site data or private browsing. Import a backup if available; a project link alone cannot restore local data.'] },
    { title: ['为什么导入后 ERC 报错？', 'Why does ERC report errors after import?'], body: ['先找缺失符号、引脚类型、未连接标记、结点和封装映射问题，对照源工程网表。不要直接删除报警或把所有未连接脚接地。特殊符号或源文件遗漏可能需要补充项目库。', 'Check missing symbols, pin types, no-connect markers, junctions and footprint mappings against the source netlist. Do not simply remove warnings or ground every unused pin. Special or missing symbols may require additions to the project library.'] },
    { title: ['自动布线为什么没有全通？', 'Why did autorouting leave connections?'], body: ['检查布局是否拥挤、线宽间距是否合理、板框和禁布区域是否阻断通道、层数是否正确。先改善布局，再尝试更多布线层；不要为了全通绕过天线净空或制造规则。', 'Check placement density, width and clearance, blocked channels at outlines or keepouts, and layer count. Improve placement before adding routing layers. Do not bypass antenna clearance or manufacturing rules just to complete routing.'] },
    { title: ['AI 无法调用怎么办？', 'What if AI requests fail?'], body: ['在 AI 配置中检查 Key、模型与协议匹配的地址。401 / 403 检查权限与令牌；模型不存在时核对模型 ID；网络错误需检查服务是否允许浏览器跨域请求。只支持 OpenAI 协议的地址不能直接用于当前 Anthropic 调用。', 'Check the key, model and protocol-compatible URL in AI settings. For 401 / 403, check permissions and credentials; for missing models, verify the model ID. Network failures may indicate the service disallows browser cross-origin requests. An OpenAI-only endpoint cannot serve the current Anthropic calls directly.'] },
    { title: ['3D 占位是否影响制造？', 'Do 3D placeholders affect fabrication?'], body: ['占位影响外观与机械检查，不直接改变焊盘和 Gerber。仍须核对实际封装、极性和器件高度；模型看起来正常也不证明焊盘映射正确。', 'Placeholders affect visual and mechanical review, not pad geometry or Gerber directly. Still verify the footprint, polarity and height. A correct-looking model does not prove the pad mapping is correct.'] },
    { title: ['刷新项目或文档页出现 404？', 'Why do project or docs pages return 404 on refresh?'], body: ['静态服务器没有配置 SPA 路由回退。将 /p/... 和 /docs 等页面请求回退到 index.html；检查构建资源路径和缓存，再直接刷新该地址验证。', 'The static host is missing SPA fallback. Serve index.html for page paths such as /p/... and /docs. Check asset paths and caching, then refresh the URL directly to verify.'] },
    { title: ['触屏和快捷键怎么用？', 'How do touch gestures and shortcuts work?'], body: ['单指选择或拖动，双指平移与捏合缩放。桌面可用空格拖动平移、⌘/Ctrl+Z 撤销、⌘/Ctrl+K 搜索命令。使用画布工具栏查看当前工具；手机属性面板默认关闭，可手动展开。', 'Use one finger to select or drag, and two fingers to pan and pinch. On desktop, Space-drag pans, ⌘/Ctrl+Z undoes and ⌘/Ctrl+K opens commands. Check the canvas toolbar for the active tool. On phones, expand the initially collapsed properties panel.'] }
  ] }
];
