import {it,expect,beforeAll} from 'vitest';
import {emptyBoard,BoardFootprintSchema,type Trace} from '../src/model/board.js';
import {registerFootprints} from '../src/library/registry.js';
import {RULE_SETS} from '../src/model/project.js';
import {routeDifferentialPair,compensatePair,pairTraceLength} from '../src/board/differentialRoute.js';
import {autoroute} from '../src/board/autoroute.js';
import {computeRatsnest} from '../src/board/ratsnest.js';
import {runDrc} from '../src/board/drc.js';
beforeAll(()=>registerFootprints([{id:'test:pair-pad',name:'pad',body:{w:.3,h:.3},height:1,description:'',pads:[{number:'1',x:0,y:0,w:.15,h:.15,shape:'rect',drill:0,npth:false}]}]));
function fixture(){const b=emptyBoard();b.netClasses[0].traceWidth=.2;b.netClasses[0].clearance=.15;b.outline=[{x:0,y:0},{x:40,y:0},{x:40,y:25},{x:0,y:25}];b.differentialPairs=[{positive:'P',negative:'N',gap:.2,tolerance:.03,maxSkew:.05}];b.footprints=[[5,10,'P'],[30,10,'P'],[5,10.4,'N'],[30,10.4,'N']].map(([x,y,net],i)=>BoardFootprintSchema.parse({id:`f${i}`,ref:`J${i}`,footprintId:'test:pair-pad',x,y,padNets:{'1':net}}));return b;}
it('routes both nets in a common corridor and preserves the source',()=>{const b=fixture(),before=JSON.stringify(b);const r=autoroute(b,RULE_SETS[0],{timeBudgetMs:4000});expect(r.routed).toBe(2);expect(r.traces).toHaveLength(2);expect(r.vias).toEqual([]);expect(JSON.stringify(b)).toBe(before);const work={...b,traces:r.traces.map((t,i)=>({...t,id:`t${i}`}))};expect(computeRatsnest(work).unrouted).toBe(0);expect(runDrc(work,RULE_SETS[0]).errors).toBe(0);expect(Math.abs(pairTraceLength(r.traces[0].points)-pairTraceLength(r.traces[1].points))).toBeLessThanOrEqual(.05);});
it('refuses a half-selected pair and never routes it as independent nets',()=>{const r=autoroute(fixture(),RULE_SETS[0],{nets:['P']});expect(r.traces).toEqual([]);expect(r.failed[0].reason).toContain('both');});
it('preserves existing pair copper and refuses unsupported partial repair',()=>{const b=fixture();b.traces=[{id:'existing',net:'P',layer:'F.Cu',width:.2,points:[{x:5,y:10},{x:7,y:10}]}];const r=autoroute(b,RULE_SETS[0]);expect(r.traces).toEqual([]);expect(b.traces[0].id).toBe('existing');expect(r.failed[0].reason).toContain('Existing');});
it('adds exact planar length with 45-degree compensation and refuses blocked tuning',()=>{const a:Omit<Trace,'id'>={net:'P',layer:'F.Cu',width:.2,points:[{x:0,y:0},{x:20,y:0}]},b={...a,net:'N',points:[{x:0,y:1},{x:22,y:1}]};const r=compensatePair(a,b,.01,()=>true);expect(r).not.toBeNull();expect(pairTraceLength(r!.points)).toBeCloseTo(22,6);expect(a.points).toHaveLength(2);expect(compensatePair(a,b,.01,()=>false)).toBeNull();});
it('routes the pair around an obstacle atomically within its skew tolerance',()=>{const b=fixture();b.traces=[{id:'wall',net:'OTHER',layer:'F.Cu',width:2,points:[{x:17,y:7},{x:17,y:12}]}];const r=routeDifferentialPair(b,RULE_SETS[0],b.differentialPairs![0],{deadline:Date.now()+6000});expect(r.reason).toBeUndefined();expect(r.traces).toHaveLength(2);expect(Math.abs(pairTraceLength(r.traces[0].points)-pairTraceLength(r.traces[1].points))).toBeLessThanOrEqual(.05);});
it('compensates the shorter lane when endpoint orientation changes',()=>{const b=fixture();b.footprints[1].x=30;b.footprints[1].y=17;b.footprints[3].x=30.4;b.footprints[3].y=17;const r=routeDifferentialPair(b,RULE_SETS[0],b.differentialPairs![0],{deadline:Date.now()+5000});expect(r.reason).toBeUndefined();expect(r.compensated).toBe(true);expect(Math.abs(pairTraceLength(r.traces[0].points)-pairTraceLength(r.traces[1].points))).toBeLessThanOrEqual(.05);});
it('returns neither lane when the pair has no common allowed layer',()=>{const b=fixture();b.netClasses[0].allowedLayers=['B.Cu'];const r=autoroute(b,RULE_SETS[0],{timeBudgetMs:2000});expect(r.routed).toBe(0);expect(r.traces).toEqual([]);expect(r.failed).toHaveLength(2);});
