import {it,expect,beforeAll} from 'vitest';
import {solveCopperThermal,powerThermalReport} from '../src/board/powerThermal.js';
import {emptyBoard,BoardFootprintSchema} from '../src/model/board.js';
import {registerFootprints} from '../src/library/registry.js';
beforeAll(()=>registerFootprints([{id:'power:pad',name:'pad',body:{w:1,h:1},height:1,description:'',pads:[{number:'1',x:0,y:0,w:1,h:1,shape:'rect',drill:0,npth:false}]}]));
const p={currentA:2,copperThicknessMm:.035,ambientC:25};
function board(){const b=emptyBoard();b.netClasses[0].power=p;b.netClasses[0].nets=['VCC'];b.footprints=[5,25].map((x,i)=>BoardFootprintSchema.parse({id:`f${i}`,ref:`J${i}`,footprintId:'power:pad',x,y:10,padNets:{'1':'VCC'}}));b.traces=[{id:'t',net:'VCC',layer:'F.Cu',width:.5,points:[{x:5,y:10},{x:25,y:10}]}];return b;}
it('matches analytic resistance, I*R drop and I²R dissipation without inventing temperature',()=>{const r=powerThermalReport(board())[0],ohms=16.8e-6*20/(.5*.035);expect(r.resistanceOhm).toBeCloseTo(ohms,9);expect(r.dropV).toBeCloseTo(2*ohms,9);expect(r.lossW).toBeCloseTo(4*ohms,9);expect(r.riseC).toBeNull();expect(r.status).toBe('electrical-only');});
it('solves thermal-resistivity feedback and detects lack of a stable equilibrium',()=>{const r=solveCopperThermal(.1,{...p,thermalResistanceKPerW:10});expect(r.riseC).toBeCloseTo(r.lossW!*10,9);expect(r.resistanceOhm).toBeCloseTo(.1*(1+.0039*r.riseC!),9);expect(solveCopperThermal(1,{...p,thermalResistanceKPerW:100}).status).toBe('unstable');});
it('reports zero-current heating as zero and rejects invalid numeric inputs',()=>{expect(solveCopperThermal(.1,{...p,currentA:0,thermalResistanceKPerW:20}).riseC).toBe(0);expect(()=>solveCopperThermal(NaN,p)).toThrow();});
it('refuses branched, disconnected and plane-shunted paths rather than summing them',()=>{const b=board();b.traces.push({id:'branch',net:'VCC',layer:'F.Cu',width:.5,points:[{x:15,y:10},{x:15,y:15}]});expect(powerThermalReport(b)[0].status).toBe('unassessed');b.traces.pop();b.zones.push({id:'z',net:'VCC',layer:'F.Cu',polygon:b.outline,thermal:'solid',thermalGap:.3,spokeWidth:.4,clearance:0});expect(powerThermalReport(b)[0].status).toBe('unassessed');});
it('includes series neck-down resistance and raises configured drop/rise warnings',()=>{const b=board();b.traces[0].points[1]={x:15,y:10};b.traces.push({id:'narrow',net:'VCC',layer:'F.Cu',width:.1,points:[{x:15,y:10},{x:25,y:10}]});b.netClasses[0].power={...p,thermalResistanceKPerW:20,maxDropV:.01,maxRiseC:.01};const r=powerThermalReport(b)[0];expect(r.minimumWidthMm).toBe(.1);expect(r.warnings).toHaveLength(2);});
it('does not count overlapping backtracking copper as a valid series resistor',()=>{const b=board();b.traces[0].points=[{x:5,y:10},{x:20,y:10},{x:15,y:10},{x:25,y:10}];expect(powerThermalReport(b)[0].status).toBe('unassessed');});
