/**
 * Tracelet MCP server（stdio）：把内核命令暴露为工具，供 Claude Code / Claude Desktop 等 MCP 客户端调用。
 * 启动：tracelet serve --mcp [--file project.eda.json]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import {
  parseProject, serializeProject, createProject, createDemoProject, ProjectEditor, sch, pcb, buildSchematicNetlist, runSchematicErc, runDrc, computeRatsnest, reviewSchematic, ruleSetOf,
  getSymbol, findPin, searchParts, BUILTIN_PARTS, BUILTIN_SYMBOLS, registeredSymbols, autoroute, exportFabFiles, importKicadProject, diffBoardFromSchematic, type Project
  , importEasyEdaProject, PROJECT_TEMPLATES, createFromTemplate, exportSchematicPdf, exportAssemblyPdf, footprintFromName, importLibraryFile, lib, type SymbolDef, type FootprintDef
} from '@tracelet/kernel';

interface State { file: string | null; editor: ProjectEditor | null }

export function createMcpServer(initialFile?: string): McpServer {
  const state: State = { file: null, editor: null };
  const server = new McpServer({ name: 'tracelet', version: '0.1.0' });
  const text = (v: unknown) => ({ content: [{ type: 'text' as const, text: typeof v === 'string' ? v : JSON.stringify(v, null, 2) }] });
  const need = (): ProjectEditor => { if (!state.editor) throw new Error('没有打开的项目：先调用 open_project 或 new_project'); return state.editor; };
  const autosave = () => { if (state.file && state.editor) writeFileSync(state.file, serializeProject(state.editor.project)); };
  const open = (p: Project, file: string | null) => { state.editor = new ProjectEditor(p); state.file = file; };
  const sheetIdOf = (ed: ProjectEditor, name?: string) => (name ? ed.project.schematic.sheets.find((s) => s.name === name || s.id === name)?.id : undefined) ?? ed.project.schematic.sheets[0].id;
  const findComp = (p: Project, ref: string) => { for (const s of p.schematic.sheets) { const c = s.components.find((x) => x.ref.toLowerCase() === ref.toLowerCase()); if (c) return { c, sheet: s }; } return null; };
  const parsePin = (s: string) => { const m = /^([^.]+)\.(.+)$/.exec(s.trim()); return m ? { ref: m[1], pin: m[2] } : null; };
  const summary = (p: Project) => {
    const nl = buildSchematicNetlist(p.schematic), erc = runSchematicErc(p.schematic, nl), rules = ruleSetOf(p), drc = runDrc(p.board, rules), rats = computeRatsnest(p.board, rules);
    return { file: state.file, name: p.name, sheets: p.schematic.sheets.map((s) => ({ id: s.id, name: s.name, components: s.components.filter((c) => !getSymbol(c.symbolId).power).length })), components: p.schematic.sheets.flatMap((s) => s.components).filter((c) => !getSymbol(c.symbolId).power).map((c) => `${c.ref} ${c.value}`), nets: nl.nets.length, unconnectedPins: nl.unconnectedPins.map((x) => `${x.ref}.${x.pinName}`), erc: { errors: erc.errors, warnings: erc.warnings }, drc: { errors: drc.errors, warnings: drc.warnings }, pcb: { footprints: p.board.footprints.length, traces: p.board.traces.length, vias: p.board.vias.length, unrouted: `${rats.unrouted}/${rats.total}`, copperCount: p.board.copperCount }, rules: rules.name };
  };

  server.registerTool('open_project', { title: '打开项目', description: '打开 .eda.json 项目文件', inputSchema: { file: z.string().describe('文件路径') } }, async ({ file }) => { const f = resolve(file); open(parseProject(readFileSync(f, 'utf8')), f); return text(summary(state.editor!.project)); });
  server.registerTool('new_project', { title: '新建项目', description: '新建项目并保存到文件', inputSchema: { file: z.string(), name: z.string().optional(), layers: z.number().optional().describe('2 或 4'), demo: z.boolean().optional().describe('使用 ESP32 示例内容') } }, async ({ file, name, layers, demo }) => { const p = demo ? createDemoProject() : createProject({ name: name ?? '未命名项目', copperCount: layers === 4 ? 4 : 2 }); if (name && demo) p.name = name; const f = resolve(file); mkdirSync(dirname(f), { recursive: true }); open(p, f); autosave(); return text(summary(p)); });
  server.registerTool('save_project', { title: '保存项目', description: '保存当前项目（可指定新路径）', inputSchema: { file: z.string().optional() } }, async ({ file }) => { const ed = need(); if (file) state.file = resolve(file); if (!state.file) throw new Error('未指定文件'); writeFileSync(state.file, serializeProject(ed.project)); return text(`已保存 ${state.file}`); });
  server.registerTool('import_kicad', { title: '导入 KiCad', description: '导入 KiCad 工程（多个 .kicad_sch = 多页，一个 .kicad_pcb）', inputSchema: { files: z.array(z.string()), out: z.string().optional().describe('保存为 .eda.json') } }, async ({ files, out }) => { const schs = files.filter((f) => f.endsWith('.kicad_sch')).map((f) => ({ name: f.split('/').pop()!.replace(/\.kicad_sch$/, ''), text: readFileSync(resolve(f), 'utf8') })); const pcbFile = files.find((f) => f.endsWith('.kicad_pcb')); const r = importKicadProject({ name: (pcbFile ?? files[0]).split('/').pop()!.replace(/\.kicad_(sch|pcb)$/, ''), schematics: schs, pcb: pcbFile ? readFileSync(resolve(pcbFile), 'utf8') : undefined }); open(r.project, out ? resolve(out) : null); autosave(); return text({ warnings: r.warnings, ...summary(r.project) }); });
  server.registerTool('project_summary', { title: '项目概览', description: '图纸、元件、网络、ERC/DRC、PCB 统计', inputSchema: {} }, async () => text(summary(need().project)));
  server.registerTool('get_netlist', { title: '网表', description: '每个网络及其引脚', inputSchema: {} }, async () => text(buildSchematicNetlist(need().project.schematic).nets.map((n) => ({ name: n.name, pins: n.pins.map((x) => `${x.ref}.${x.pinNumber}(${x.pinName})`) }))));
  server.registerTool('get_component', { title: '元件详情', description: '值、封装、引脚与网络', inputSchema: { ref: z.string() } }, async ({ ref }) => { const ed = need(); const f = findComp(ed.project, ref); if (!f) throw new Error(`没有位号 ${ref}`); const nl = buildSchematicNetlist(ed.project.schematic); const sym = getSymbol(f.c.symbolId); return text({ ref: f.c.ref, value: f.c.value, symbol: sym.name, footprint: f.c.footprint, sheet: f.sheet.name, pins: sym.pins.map((p) => ({ number: p.number, name: p.name, type: p.type, net: nl.pinNet.get(`${f.c.id}:${p.number}`) ?? '' })) }); });
  server.registerTool('run_erc', { title: 'ERC', description: '电气规则检查', inputSchema: {} }, async () => { const r = runSchematicErc(need().project.schematic); return text({ errors: r.errors, warnings: r.warnings, items: r.items.map((i) => ({ id: i.id, severity: i.severity, rule: i.rule, message: i.message, refs: i.refs, why: i.why })) }); });
  server.registerTool('run_drc', { title: 'DRC', description: 'PCB 设计规则检查 + 未布线数', inputSchema: { rules: z.string().optional().describe('jlc | jlcpcb | generic') } }, async ({ rules }) => { const ed = need(); const rs = ruleSetOf({ ...ed.project, settings: { ...ed.project.settings, ruleSetId: rules ?? ed.project.settings.ruleSetId } }); const r = runDrc(ed.project.board, rs); const rats = computeRatsnest(ed.project.board, rs); return text({ rules: rs.id, errors: r.errors, warnings: r.warnings, unrouted: rats.unrouted, total: rats.total, items: r.items.map((i) => ({ id: i.id, severity: i.severity, rule: i.rule, message: i.message, refs: i.refs, why: i.why, location: i.location })) }); });
  server.registerTool('review_schematic', { title: '设计审查', description: '确定性经验规则：去耦 / 上拉 / 限流', inputSchema: {} }, async () => text(reviewSchematic(need().project.schematic)));
  server.registerTool('list_symbols', { title: '符号列表', description: '内置与项目内符号 id', inputSchema: {} }, async () => text([...BUILTIN_SYMBOLS, ...registeredSymbols()].map((s) => ({ id: s.id, name: s.name, kind: s.kind, pins: s.pins.length }))));
  server.registerTool('search_parts', { title: '搜索零件', description: '内置零件目录', inputSchema: { query: z.string(), category: z.string().optional() } }, async ({ query, category }) => text(searchParts(query, BUILTIN_PARTS, category).slice(0, 10).map((p) => ({ partId: p.id, mpn: p.mpn, maker: p.maker, description: p.description, symbol: p.symbolId, footprint: p.footprintId }))));
  server.registerTool('place_component', { title: '放置元件', description: '在图纸上放置元件（symbol 为符号 id 或 partId）', inputSchema: { symbol: z.string(), value: z.string().optional(), x: z.number().optional().describe('mil'), y: z.number().optional().describe('mil'), sheet: z.string().optional() } }, async ({ symbol, value, x, y, sheet }) => { const ed = need(); const part = BUILTIN_PARTS.find((p) => p.id === symbol || p.mpn === symbol); const symbolId = part?.symbolId ?? symbol; getSymbol(symbolId); const sid = sheetIdOf(ed, sheet); const cur = ed.project.schematic.sheets.find((s) => s.id === sid)!; const maxX = Math.max(1000, ...cur.components.map((c) => c.x)); const r = sch.placeComponent(ed.project, { sheetId: sid, symbolId, center: { x: x ?? maxX + 2000, y: y ?? 2000 }, value: value ?? part?.value, footprint: part?.footprintId, props: part ? { mpn: part.mpn, lcsc: part.lcsc ?? '' } : undefined }); ed.dispatch(r.command); autosave(); return text({ ref: r.ref, id: r.id }); });
  server.registerTool('connect_pins', { title: '连线', description: '连接两个引脚，格式 ref.pin（编号或名称）', inputSchema: { a: z.string(), b: z.string() } }, async ({ a, b }) => { const ed = need(); const pa = parsePin(a), pb = parsePin(b); if (!pa || !pb) throw new Error('格式应为 ref.pin'); const fa = findComp(ed.project, pa.ref), fb = findComp(ed.project, pb.ref); if (!fa || !fb) throw new Error('位号不存在'); if (fa.sheet.id !== fb.sheet.id) throw new Error('不在同一页，请用 add_net_label'); const num = (c: typeof fa.c, pin: string) => (findPin(c, pin) ? pin : getSymbol(c.symbolId).pins.find((p) => p.name === pin)?.number); const na = num(fa.c, pa.pin), nb = num(fb.c, pb.pin); if (!na || !nb) throw new Error('引脚不存在'); ed.dispatch(sch.connectPins(fa.sheet.id, { componentId: fa.c.id, pin: na }, { componentId: fb.c.id, pin: nb })); autosave(); return text('已连线'); });
  server.registerTool('add_net_label', { title: '网络标签', description: '给引脚加网络标签（跨页 / 远距离连接）', inputSchema: { pin: z.string(), net: z.string() } }, async ({ pin, net }) => { const ed = need(); const pp = parsePin(pin); if (!pp) throw new Error('格式应为 ref.pin'); const f = findComp(ed.project, pp.ref); if (!f) throw new Error('位号不存在'); const d = getSymbol(f.c.symbolId).pins.find((p) => p.number === pp.pin || p.name === pp.pin); const g = d && findPin(f.c, d.number); if (!g) throw new Error('引脚不存在'); const dir = { x: Math.sign(g.end.x - g.base.x), y: Math.sign(g.end.y - g.base.y) }; const tip = { x: g.end.x + dir.x * 200, y: g.end.y + dir.y * 200 }; ed.begin('网络标签'); ed.dispatch(sch.addWire(f.sheet.id, [g.end, tip])); ed.dispatch(sch.addLabel(f.sheet.id, net, tip)); ed.commit(); autosave(); return text('已添加'); });
  server.registerTool('set_component_value', { title: '修改值', description: '修改元件的值', inputSchema: { ref: z.string(), value: z.string() } }, async ({ ref, value }) => { const ed = need(); const f = findComp(ed.project, ref); if (!f) throw new Error('位号不存在'); ed.dispatch(sch.setComponentValue(f.sheet.id, f.c.id, value)); autosave(); return text('已修改'); });
  server.registerTool('sync_to_pcb', { title: '同步到 PCB', description: '原理图 → PCB（新增/删除封装、更新焊盘网络）', inputSchema: {} }, async () => { const ed = need(); const d = diffBoardFromSchematic(ed.project); ed.dispatch(pcb.syncFromSchematic()); autosave(); return text({ added: d.added, removed: d.removed, updated: d.updated.length }); });
  server.registerTool('move_footprint', { title: '移动封装', description: 'PCB 上移动封装（mm）', inputSchema: { ref: z.string(), x: z.number(), y: z.number(), rotation: z.number().optional() } }, async ({ ref, x, y, rotation }) => { const ed = need(); const fp = ed.project.board.footprints.find((f) => f.ref.toLowerCase() === ref.toLowerCase()); if (!fp) throw new Error('PCB 上没有该封装'); ed.begin('移动'); ed.dispatch(pcb.moveFootprint(fp.id, { x, y })); if (rotation !== undefined) ed.dispatch(pcb.rotateFootprint(fp.id, rotation - fp.rotation)); ed.commit(); autosave(); return text('已移动'); });
  server.registerTool('set_board_outline', { title: '板框', description: '矩形板框（mm）', inputSchema: { width: z.number(), height: z.number() } }, async ({ width, height }) => { const ed = need(); ed.dispatch(pcb.setOutlineRect(width, height)); autosave(); return text('已设置'); });
  server.registerTool('autoroute', { title: '自动布线', description: '内置 A* 布线器布完未布线连接并应用（可 undo）', inputSchema: { nets: z.array(z.string()).optional() } }, async ({ nets }) => { const ed = need(); const r = autoroute(ed.project.board, ruleSetOf(ed.project), { nets }); if (r.traces.length) ed.dispatch(pcb.applyRoutes(r.traces, r.vias)); autosave(); return text({ routed: r.routed, total: r.total, failed: r.failed, traces: r.traces.length, vias: r.vias.length }); });
  server.registerTool('export_fab', { title: '导出制造文件', description: 'Gerber + Excellon + BOM + 坐标写入目录', inputSchema: { dir: z.string() } }, async ({ dir }) => { const ed = need(); const files = exportFabFiles(ed.project, { netlist: true }); mkdirSync(resolve(dir), { recursive: true }); for (const f of files) writeFileSync(resolve(dir, f.name), f.content); return text({ dir: resolve(dir), files: files.map((f) => f.name) }); });
  server.registerTool('import_easyeda', { title: '导入嘉立创 EDA', description: '导入 EasyEDA 标准版 JSON（原理图 / PCB / 工程导出）', inputSchema: { files: z.array(z.string()), out: z.string().optional() } }, async ({ files, out }) => { const r = importEasyEdaProject({ name: files[0].split('/').pop()!.replace(/\.json$/i, ''), files: files.map((f) => ({ name: f.split('/').pop()!, text: readFileSync(resolve(f), 'utf8') })) }); open(r.project, out ? resolve(out) : null); autosave(); return text({ warnings: r.warnings, ...summary(r.project) }); });
  server.registerTool('list_templates', { title: '项目模板', description: '可用的新建项目模板（blank / esp32 / stm32 / arduino）', inputSchema: {} }, async () => text(PROJECT_TEMPLATES.map((t) => ({ id: t.id, name: t.name, description: t.description }))));
  server.registerTool('new_from_template', { title: '按模板新建', description: '用模板新建项目并保存到文件', inputSchema: { file: z.string(), template: z.string().describe('blank | esp32 | stm32 | arduino'), name: z.string().optional(), layers: z.number().optional() } }, async ({ file, template, name, layers }) => { const p = createFromTemplate(template, { name, copperCount: layers === 4 ? 4 : 2 }); const f = resolve(file); mkdirSync(dirname(f), { recursive: true }); open(p, f); autosave(); return text(summary(p)); });
  server.registerTool('export_pdf', { title: '导出 PDF', description: '原理图 PDF 与装配图 PDF 写入文件', inputSchema: { schematic: z.string().optional().describe('原理图 PDF 路径'), assembly: z.string().optional().describe('装配图 PDF 路径') } }, async ({ schematic, assembly }) => { const ed = need(); const outp: string[] = []; if (schematic) { writeFileSync(resolve(schematic), exportSchematicPdf(ed.project), 'latin1'); outp.push(resolve(schematic)); } if (assembly) { writeFileSync(resolve(assembly), exportAssemblyPdf(ed.project), 'latin1'); outp.push(resolve(assembly)); } return text({ files: outp }); });
  server.registerTool('generate_footprint', { title: '参数化封装', description: '按 KiCad 风格名（LQFP-48_7x7mm_P0.5mm、SOIC-8_3.9x4.9mm_P1.27mm、R_0603_1608Metric、PinHeader_1x04_P2.54mm_Vertical、SOT-23-5…）生成封装并加入项目库', inputSchema: { name: z.string() } }, async ({ name }) => { const ed = need(); const def = footprintFromName(name); if (!def) throw new Error('无法识别的封装名'); ed.dispatch(lib.addLibraryItems({ footprints: [def] })); autosave(); return text({ id: def.id, name: def.name, pads: def.pads.length, body: def.body }); });
  server.registerTool('import_library', { title: '导入库文件', description: '把 .kicad_sym / .kicad_mod 导入项目库', inputSchema: { files: z.array(z.string()) } }, async ({ files }) => { const ed = need(); const symbols: SymbolDef[] = [], footprints: FootprintDef[] = [], warnings: string[] = []; for (const f of files) { const r = importLibraryFile(f.split('/').pop()!, readFileSync(resolve(f), 'utf8')); symbols.push(...r.symbols); footprints.push(...r.footprints); warnings.push(...r.warnings); } ed.dispatch(lib.addLibraryItems({ symbols, footprints })); autosave(); return text({ symbols: symbols.map((x) => x.id), footprints: footprints.map((x) => x.id), warnings }); });
  server.registerTool('undo', { title: '撤销', description: '撤销上一步修改', inputSchema: {} }, async () => { const ed = need(); const label = ed.undoLabel; const ok = ed.undo(); autosave(); return text(ok ? `已撤销：${label}` : '没有可撤销的操作'); });

  if (initialFile) { try { const f = resolve(initialFile); open(parseProject(readFileSync(f, 'utf8')), f); } catch (e) { console.error(`无法打开 ${initialFile}: ${(e as Error).message}`); } }
  return server;
}

export async function serveMcp(initialFile?: string) {
  const server = createMcpServer(initialFile);
  await server.connect(new StdioServerTransport());
}
